### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by Sergimaster** [yellows8/3ds_dsiwarehax_installer#10]
I only use the dsiwarehax installer on Zelda Four swords and when i open the "hacked" Zelda on o3ds 11.5 the Screen is in White 
Sorry for m'y Bad english

**Comment by WinterMute** [comment]
Did you place boot.nds on the root of your SD card? https://github.com/devkitPro/nds-hb-menu/releases is good.

**Comment by MelonGx** [comment]
4swordshax savedata is only compatible with OLD libnds compiled B9STool.
See this.
https://github.com/Plailect/b9sTool/releases/tag/v2.1.0
If any update of B9STool causes white screen again, you need to compile it with OLD libnds or ask the author for an update.

**Comment by fincs** [comment]
That's the most backwards possible solution to the problem. The real fix would be to rebuild 4swordshax using the latest version of [nds-bootloader](https://github.com/devkitPro/nds-bootloader).
