### ISSUE TITLE
Would be possible do the save injection on the .bin backup?

### ISSUE THREAD

**Issue by kurocygnus** [yellows8/3ds_dsiwarehax_installer#6]

**Comment by BlackAc3** [comment]
I also curious, is it possible to use someone backup ? lets say they injected then backup the .bin and upload to us

**Comment by kurocygnus** [comment]
> I also curious, is it possible to use someone backup ? lets say they injected then backup the .bin and upload to us

AFAIK the .bin have a unique encryption to each console.

**Comment by BlackAc3** [comment]
what about we compare the .bin file with the one we have? if someone know the offset for the unique encryption key, then it will be possible to reuse it. one problem is, will the .bin backup still retain the DSiware hax savefile?

**Comment by kurocygnus** [comment]
I guess it will, because when you backup the game, you backup the savegame together, so it's really possible to inject the savegame in the .bin file.

**Comment by yellows8** [comment]
{console-unique crypto} <- indeed
